# Generated by Django 4.1 on 2022-09-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skill',
            new_name='skills',
        ),
    ]
