# Generated by Django 4.1 on 2022-09-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_rename_skill_profile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='skill',
        ),
    ]
