# Generated by Django 4.1 on 2022-09-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_profile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college_cgpa',
            field=models.FloatField(default=3.9, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
